-- supabase/126_xtell_memory.sql — XTell masters' memory (owner, Oct 2-3:
-- "continue and read all"; each master summarizes its own memory with its
-- own model, "since we want to test each model's summarization
-- capability"). The design is docs/XTELL-MEMORY.md.
--
--   xtell_messages   one row per message of a conversation: the visitor's
--                    messages and every master's answers. `seq` is one
--                    database-wide number, so an insert needs no lock and
--                    order within a conversation is `order by seq`; gaps do
--                    not matter. A visitor's message is stored once per
--                    question (qid) however many masters answer it, and a
--                    master's answer once per question. Answers carry what
--                    the master actually read (input_tokens) and the cost.
--   xtell_memories   a master's notebook in one conversation: each summary
--                    a new row, `through_seq` the last message folded in.
--                    Never updated; the newest is the memo in use, the older
--                    ones stay for comparing how each model summarizes.
--   ai_models.context_window
--                    each model's window in tokens, edited in /admin/models;
--                    the code uses 100k while it is empty.
--
-- Existing conversations are copied from xtell_readings.turns into
-- xtell_messages, in their order; the code goes on writing both until
-- everything reads the new table. A conversation already copied is skipped,
-- so this is safe to re-run. Nothing is removed.
--
-- Access: a visitor reads only the messages and memos of their own
-- conversations; only the server writes (service role), after checking the
-- conversation is the caller's. Both tables are revoked from public, anon
-- and authenticated by name (pitfalls 15 and 16), then SELECT is granted
-- back to authenticated under the owner policy. Deleting a conversation, or
-- the account that owns it, deletes its messages and memos (cascade).
--
-- Run by hand. Dev and prod share this database.

begin;

create table if not exists public.xtell_messages (
  seq           bigint generated by default as identity primary key,
  reading_id    uuid not null references public.xtell_readings(id) on delete cascade,
  role          text not null check (role in ('user', 'assistant')),
  content       text not null,
  model_id      text,                 -- an answer: the master's ai_models id
  model_name    text,                 -- its name when it answered
  provider      text,
  qid           text,                 -- the question this belongs to
  "to"          text[],               -- a question put to some masters only
  seats         text[],               -- the masters seated when it was asked
  input_tokens  integer,              -- an answer: what the master read
  cost          numeric,              -- an answer: list cost in USD
  created_at    timestamptz not null default now()
);

create index if not exists xtell_messages_conversation on public.xtell_messages (reading_id, seq);
-- One visitor message per question, one answer per master per question.
create unique index if not exists xtell_messages_one_question on public.xtell_messages (reading_id, qid)
  where role = 'user' and qid is not null;
create unique index if not exists xtell_messages_one_answer on public.xtell_messages (reading_id, qid, model_id)
  where role = 'assistant' and qid is not null and model_id is not null;

create table if not exists public.xtell_memories (
  id             uuid primary key default gen_random_uuid(),
  reading_id     uuid not null references public.xtell_readings(id) on delete cascade,
  model_id       text not null,
  model_name     text,
  through_seq    bigint not null,
  text           text not null,
  input_tokens   integer,
  output_tokens  integer,
  cost           numeric,
  created_at     timestamptz not null default now(),
  unique (reading_id, model_id, through_seq)
);

alter table public.ai_models add column if not exists context_window integer
  check (context_window is null or context_window > 0);

-- Access.
alter table public.xtell_messages enable row level security;
alter table public.xtell_memories enable row level security;
revoke all on table public.xtell_messages from public, anon, authenticated;
revoke all on table public.xtell_memories from public, anon, authenticated;
grant select on table public.xtell_messages to authenticated;
grant select on table public.xtell_memories to authenticated;
grant select, insert, update, delete on table public.xtell_messages to service_role;
grant select, insert, update, delete on table public.xtell_memories to service_role;

drop policy if exists "xtell_messages: owner read" on public.xtell_messages;
create policy "xtell_messages: owner read" on public.xtell_messages for select to authenticated
  using (exists (select 1 from public.xtell_readings r where r.id = reading_id and r.user_id = auth.uid()));
drop policy if exists "xtell_memories: owner read" on public.xtell_memories;
create policy "xtell_memories: owner read" on public.xtell_memories for select to authenticated
  using (exists (select 1 from public.xtell_readings r where r.id = reading_id and r.user_id = auth.uid()));

do $$
declare s text := pg_get_serial_sequence('public.xtell_messages', 'seq');
begin
  execute format('revoke all on sequence %s from public, anon, authenticated', s);
  execute format('grant usage, select on sequence %s to service_role', s);
end $$;

-- Copy the existing conversations, in order. Each conversation's turns keep
-- their order; conversations follow each other by when they were made. The
-- numbers start after any already taken, and a conversation that already
-- has messages is left alone.
with base as (select coalesce(max(seq), 0) as b from public.xtell_messages),
src as (
  select r.id as reading_id, r.created_at as made, t.v, t.ord
  from public.xtell_readings r
  cross join lateral jsonb_array_elements(case when jsonb_typeof(r.turns) = 'array' then r.turns else '[]'::jsonb end) with ordinality as t(v, ord)
  where t.v->>'role' in ('user', 'assistant')
    and jsonb_typeof(t.v->'content') = 'string'
    and not exists (select 1 from public.xtell_messages m where m.reading_id = r.id)
)
insert into public.xtell_messages (seq, reading_id, role, content, model_id, model_name, provider, qid, "to", seats, cost, created_at)
select (select b from base) + row_number() over (order by s.made, s.reading_id, s.ord),
       s.reading_id,
       s.v->>'role',
       s.v->>'content',
       nullif(s.v->>'modelId', ''),
       nullif(s.v->>'name', ''),
       nullif(s.v->>'provider', ''),
       nullif(s.v->>'qid', ''),
       case when jsonb_typeof(s.v->'to') = 'array' then array(select jsonb_array_elements_text(s.v->'to')) end,
       case when jsonb_typeof(s.v->'seats') = 'array' then array(select jsonb_array_elements_text(s.v->'seats')) end,
       case when jsonb_typeof(s.v->'cost') = 'number' then (s.v->>'cost')::numeric end,
       case when s.v->>'ts' ~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}' then (s.v->>'ts')::timestamptz else s.made end
from src s
on conflict do nothing;

-- New messages are numbered after the copied ones.
select setval(pg_get_serial_sequence('public.xtell_messages', 'seq'),
              greatest((select coalesce(max(seq), 0) from public.xtell_messages), 1));

commit;

-- After running, each of these must be false:
--   select has_table_privilege('anon', 'public.xtell_messages', 'select');
--   select has_table_privilege('authenticated', 'public.xtell_messages', 'insert');
--   select has_table_privilege('anon', 'public.xtell_memories', 'select');
--   select has_table_privilege('authenticated', 'public.xtell_memories', 'insert');
-- And with the publishable key (no session): GET and POST on
-- /rest/v1/xtell_messages and /rest/v1/xtell_memories both answer 42501.
