-- supabase/92_showcase.sql — the museum wall.
--
-- Curation ONLY. The pictures already live in xcreates: the house prompts are
-- generated by a system account through the normal /api/xcreate pipeline, so
-- billing, job rows, provider_calls logging and storage all behave exactly as
-- they do for a user. This table records which of those outputs are hung, in
-- which room, in what order. Nothing is copied — a piece is a pointer.
--
-- The link is (xcreate_id, slot_index), not xcreate_id alone: one xcreates row
-- holds N slots, one per model, and the wall hangs a SINGLE model's picture
-- with its own name card. Pointing at the run would hang the whole comparison.
--
-- Everything the name card needs is already on the slot — provider,
-- model_name, display name, cost, options — and the prompt is on the run. That
-- is deliberate: denormalising the model onto this table would let a card
-- drift from the picture it labels, and a museum that mislabels a work is
-- worse than no museum.
--
-- Which models qualify is NOT stored here. "Newest in each family" is derived
-- at seed time from ai_models.released_at, so a new model joins the wall and
-- its predecessor leaves without anyone editing data. (An earlier draft added
-- a `showcase` key to blocked_features; that was a hand-maintained list
-- duplicating released_at, and it was reverted.)

create table if not exists showcase (
  id          uuid primary key default gen_random_uuid(),
  xcreate_id  uuid        not null references xcreates(id) on delete cascade,
  slot_index  int         not null,
  room        text        not null default 'gallery',
  title       text,
  sort_order  int         not null default 0,
  published   boolean     not null default false,
  created_at  timestamptz not null default now(),

  -- One piece per (run, slot): hanging the same picture twice is a curation
  -- mistake, not a feature.
  unique (xcreate_id, slot_index)
);

create index if not exists showcase_room_order_idx on showcase (room, sort_order);
create index if not exists showcase_published_idx  on showcase (published) where published;

-- RLS on with NO policies: the anon and authenticated keys can read nothing
-- here directly. That is intended. The wall is served by /api/showcase using
-- the service role, because every picture needs a freshly signed storage URL
-- (they expire in 24h) and the underlying xcreates rows are owner-read only.
-- Handing a browser the raw rows would give it storage paths it cannot use.
alter table showcase enable row level security;
