// ModelXD Playground (owner, Sep 14): an image-led create/remix gallery.
// Four finished artworks and two text scenario presets. Every item carries an
// image prompt and a separate, concise motion prompt; the page prefills
// XDuel (image duel) and XDirect (film) with them and never runs anything.
//
// Provenance: the vampire artwork is an original character generated by
// Codex with its built-in image generation (playground-assets/manifest.json,
// 2026-09-14, "Not a ModelXD generation or duel result"). The three game
// works are unofficial fan concepts from the same tool
// (game-gallery-assets/manifest.json). No item is an XDuel result; no model
// name, price or vote is attached. Artwork image prompts are the manifest
// strings verbatim; motion prompts and the presets were written for this
// page. image = the supplied 1672x941 PNG (lightbox); thumb = a JPEG copy of
// the same file for cards and the home hero.
export type Bilingual = { en: string; ja: string }
export type PgArtwork = {
  kind: 'artwork'
  original: boolean          // false = unofficial fan art of a named game
  slug: string
  image: string
  thumb: string
  title: Bilingual
  reference: Bilingual
  alt: Bilingual
  imagePrompt: string        // manifest prompt, verbatim (English)
  videoPrompt: Bilingual
}
export type PgPreset = {
  kind: 'preset'
  slug: string
  emoji: string
  title: Bilingual
  blurb: Bilingual
  imagePrompt: Bilingual
  videoPrompt: Bilingual
}
export type PgItem = PgArtwork | PgPreset

export const PG_ITEMS: PgItem[] = [
  {
    kind: 'artwork', original: true,
    slug: 'vampire-dinner',
    image: '/playground/vampire-dinner.png', thumb: '/playground/vampire-dinner.jpg',
    title: { en: 'Even a final boss waits for dinner.', ja: '魔王も、温め待ち。' },
    reference: { en: 'Original character. A convenience store at 2 a.m.', ja: 'オリジナルキャラクター。深夜2時のコンビニ。' },
    alt: { en: 'Original AI artwork of a dramatic vampire count waiting for a microwave bento in a Japanese convenience store while a sleepy clerk watches', ja: '深夜のコンビニで電子レンジの弁当を待つ芝居がかった吸血鬼の伯爵と、眠そうな店員を描いたオリジナルAIアートワーク' },
    imagePrompt: 'Create a landscape 16:9 original comedic game cinematic artwork. A flamboyantly dramatic original vampire count in an elaborate midnight-purple velvet cape and silver brocade vest stands inside a brightly lit Japanese convenience store at 2am, staring with intense impatience at a microwave reheating a very ordinary plastic bento dinner. He has long silver hair, angular elegant features, tiny fangs, dark gloves, an absurdly serious expression. He holds a small disposable wooden chopstick packet as if it were a legendary sword. Outside the rain-streaked windows is a moonlit Tokyo side street; inside fluorescent mint and warm cream light, colorful packaged snacks. A sleepy adult clerk in a plain teal apron watches unimpressed in the background. Strong visual joke: gothic final-boss grandeur versus mundane late-night hunger. Render richly detailed stylized 3D game cinematic, expressive face, readable clean silhouettes, cinematic lighting, high-quality material detail. Medium-wide side angle: vampire left, microwave right, both fully readable in thumbnail. Original character and original shop, no existing franchise character, no company logos, no recognizable branding, no text captions, no UI, no watermark. Single finished image, not a storyboard.',
    videoPrompt: { en: 'A 6-second cinematic shot: the microwave hums and slowly turns the bento; the vampire count leans closer, cape swaying, tapping the chopstick packet like a sword; the timer beeps, he flinches at the light as the door opens, steam rises; the sleepy clerk does not look up. Slight slow push-in, fluorescent mint and warm cream light, no text.', ja: '6秒の映像。電子レンジがうなり、弁当がゆっくり回る。吸血鬼の伯爵はマントを揺らしながら顔を近づけ、割り箸の袋を剣のように指で叩く。タイマーが鳴り、扉が開く光にひるみ、湯気が立ちのぼる。眠そうな店員は顔を上げない。ゆっくりとしたプッシュイン、蛍光灯のミントと暖色の光、文字なし。' },
  },
  {
    kind: 'artwork', original: false,
    slug: 'street-fighter',
    image: '/playground/street-fighter.png', thumb: '/playground/street-fighter.jpg',
    title: { en: 'One strike, that instant.', ja: '一撃、その瞬間。' },
    reference: { en: 'Homage to Street Fighter (CAPCOM)', ja: 'ストリートファイター（カプコン）へのオマージュ' },
    alt: { en: 'AI fan concept of Ryu from Street Fighter releasing a Hadouken in a rainy Tokyo backstreet', ja: 'ストリートファイターのリュウが雨の東京の路地で波動拳を放つAIファンアート' },
    imagePrompt: 'Use case: stylized-concept. Asset type: landscape 16:9 game fan-art gallery image for a Japanese game-show website. Create a new unofficial fan-art illustration of Ryu from Street Fighter unleashing a Hadouken in a rain-soaked Tokyo backstreet at night. Recognizable Ryu: short dark hair, red headband, white sleeveless frayed karate gi, red sparring gloves. Dynamic grounded three-quarter pose, both hands cupping the intense blue energy wave; anatomically clear hands and limbs. Wet asphalt reflects the electric blue blast and restrained red lantern lights. Render as richly painted fighting-game key art with confident ink edges, tactile brush marks, strong silhouette and depth. Medium-wide framing, figure and energy wave both readable at thumbnail size, leave breathing room around the subject for responsive cropping. Make the face and action the focal point. A single finished artwork, no panels, no UI, no lettering, no logos, no watermark. Do not reproduce an existing promotional poster.',
    videoPrompt: { en: 'A 6-second cinematic shot of the same scene: rain falls through neon light, the blue energy wave flares and streaks forward, puddles ripple, the headband tails whip in the gust, slow push-in on the face, no text.', ja: '同じ場面の6秒映像。ネオンの光の中に雨が降り、青いエネルギー波が閃いて前方へ走る。水たまりが波打ち、鉢巻きの尾が風に舞う。顔へゆっくりプッシュイン、文字なし。' },
  },
  {
    kind: 'artwork', original: false,
    slug: 'monster-hunter',
    image: '/playground/monster-hunter.png', thumb: '/playground/monster-hunter.jpg',
    title: { en: 'Painting the world of the hunt.', ja: '狩りの世界を、描く。' },
    reference: { en: 'Homage to Monster Hunter (CAPCOM)', ja: 'モンスターハンター（カプコン）へのオマージュ' },
    alt: { en: 'AI fan concept of Rathalos from Monster Hunter descending on a hunter in an ancient forest', ja: 'モンスターハンターのリオレウスが古代の森でハンターに迫るAIファンアート' },
    imagePrompt: 'Use case: stylized-concept. Asset type: landscape 16:9 game fan-art gallery image for a Japanese game-show website. Create new unofficial Monster Hunter fan art: the recognizable red fire wyvern Rathalos descending through the huge canopy of an ancient forest, confronting one armored hunter carrying an oversized great sword in the foreground. The monster has two powerful legs and two broad leathery wings, red-orange plated scales, a horned head and a heavy spiked tail; the wing membranes and silhouette must read clearly. The hunter seen three-quarter from behind establishes enormous scale. Warm shafts of late-afternoon sun, fern-covered ruins, luminous green foliage, a few embers and drifting leaves. Detailed painterly fantasy environment concept art with cinematic depth, crisp foreground silhouettes and a magnificent creature, strong separation between green forest and red monster. A single finished artwork, generous composition that survives a card crop. No injury or gore, no text, no logos, no UI, no watermark. Do not reproduce an existing promotional poster.',
    videoPrompt: { en: 'A 6-second cinematic shot: the red wyvern descends through the canopy, wings beating and scattering leaves and embers; shafts of sunlight sweep across the ruins; the hunter plants the great sword and braces; slow tilt up from hunter to monster, no text.', ja: '6秒の映像。赤い飛竜が林冠を突き抜けて舞い降り、羽ばたきで木の葉と火の粉が散る。日差しの筋が遺跡を横切り、ハンターは大剣を地に突き立てて身構える。ハンターからモンスターへゆっくりティルトアップ、文字なし。' },
  },
  {
    kind: 'artwork', original: false,
    slug: 'metal-gear',
    image: '/playground/metal-gear.png', thumb: '/playground/metal-gear.jpg',
    title: { en: 'The tension of infiltration, in one frame.', ja: '潜入の緊張を、一枚に。' },
    reference: { en: 'Homage to Metal Gear (KONAMI)', ja: 'メタルギア（コナミ）へのオマージュ' },
    alt: { en: 'AI fan concept of Solid Snake from Metal Gear crouching in an industrial hangar with a Metal Gear silhouette behind', ja: 'メタルギアのソリッド・スネークが格納庫に潜み、背後にメタルギアの影が立つAIファンアート' },
    imagePrompt: 'Use case: stylized-concept. Asset type: landscape 16:9 game fan-art gallery image for a Japanese game-show website. Create new unofficial Metal Gear fan art featuring the recognizable Solid Snake, with dark swept-back hair, dark gray headband and trailing ties, light stubble, fitted gray-blue tactical sneaking suit and harness. He crouches behind a concrete pier in a cold industrial infiltration scene, alert and looking toward a distant searchlight. No actor likeness. A vast bipedal Metal Gear machine looms as a silhouette through mist in a hangar background. Rain and shallow puddles catch sparse amber warning lights against cool blue-gray steel. The scene conveys stealth, patience and scale through negative space and a restrained cinematic composition. Painterly military-science-fiction concept art with precise material rendering and purposeful brushwork; Snake\'s face and full silhouette readable. A single finished landscape artwork, no collage, no text, no logos, no interface, no watermark, no gore. Do not reproduce an existing game screenshot or poster.',
    videoPrompt: { en: 'A 6-second cinematic shot: rain drips from the pier, the searchlight sweeps past and Snake holds still, then eases forward; mist drifts and the Metal Gear silhouette shifts in the hangar; amber warning lights pulse; slow lateral dolly, no text.', ja: '6秒の映像。桟橋から雨が滴り、サーチライトが通り過ぎる間スネークは動かず、そのあと静かに前へ。霧が流れ、格納庫のメタルギアの影が揺れる。琥珀色の警告灯が明滅。ゆっくりとした横ドリー、文字なし。' },
  },
  {
    kind: 'preset',
    slug: 'boss-claw-machine', emoji: '👾🎰',
    title: { en: 'Final boss vs claw machine', ja: 'ラスボス vs クレーンゲーム' },
    blurb: { en: 'A world-ending villain meets the one enemy he cannot beat.', ja: '世界を滅ぼす魔王が、唯一勝てない相手と出会う。' },
    imagePrompt: { en: 'A towering armored final boss with glowing purple eyes and a tattered cape hunched over a small pink claw machine in a bright Japanese game arcade, intensely focused, the claw about to drop on a plush toy, dramatic villain lighting against cheerful pastel arcade colors, comedic contrast, richly painted illustration, landscape 16:9, original character, no text, no logos.', ja: '明るい日本のゲームセンターで、小さなピンクのクレーンゲームに覆いかぶさる、紫に光る目とぼろぼろのマントの巨大な鎧姿のラスボス。真剣そのもので、アームがぬいぐるみに落ちる直前。魔王らしい劇的なライティングと、パステルの陽気なゲーセンの対比。コメディ、密度の高いペイント調イラスト、横長16:9、オリジナルキャラクター、文字なし、ロゴなし。' },
    videoPrompt: { en: 'A 6-second shot: the claw descends slowly, the boss leans in holding his breath, cape drifting; the claw grabs the plush, lifts, and drops it at the last second; the boss slumps in defeat while arcade lights blink; subtle push-in, no text.', ja: '6秒の映像。アームがゆっくり降り、魔王は息を止めて身を乗り出し、マントが揺れる。アームがぬいぐるみをつかんで持ち上げ、最後の瞬間に落とす。魔王はがっくりと肩を落とし、ゲーセンの光が点滅。控えめなプッシュイン、文字なし。' },
  },
  {
    kind: 'preset',
    slug: 'samurai-last-train', emoji: '🗡️🚃',
    title: { en: 'The samurai who missed the last train', ja: '終電を逃した侍' },
    blurb: { en: 'Full armor, a plastic bag, and no way home.', ja: '鎧姿にレジ袋。帰る手段はない。' },
    imagePrompt: { en: 'A lone samurai in full armor standing on an empty late-night Tokyo train platform as the last train pulls away, holding a plastic convenience-store bag, shoulders slumped, light rain, neon signage reflected on the wet platform, cinematic melancholy comedy, painterly illustration, landscape 16:9, original character, no text, no logos.', ja: '深夜の東京、誰もいない駅のホームで、走り去る終電を見送る鎧姿の侍。手にはコンビニのレジ袋、肩を落としている。小雨、濡れたホームに映るネオンの看板。切なさとコメディが同居するシネマティックな一枚、ペイント調イラスト、横長16:9、オリジナルキャラクター、文字なし、ロゴなし。' },
    videoPrompt: { en: 'A 6-second shot: the train doors close and it glides away; the samurai raises a hand a second too late; a gust ruffles his sash; he sits on the bench and opens the bag; slow dolly along the platform, no text.', ja: '6秒の映像。電車の扉が閉まり、静かに走り去る。侍は一瞬遅れて手を上げる。風が帯をなびかせ、彼はベンチに座ってレジ袋を開ける。ホームに沿ってゆっくりドリー、文字なし。' },
  },
]

export const PG_ARTWORKS = PG_ITEMS.filter((i): i is PgArtwork => i.kind === 'artwork')
export const PG_PRESETS  = PG_ITEMS.filter((i): i is PgPreset => i.kind === 'preset')
/** The Japanese home's hero picture: the vampire (owner, Sep 14). */
export const PG_HERO = PG_ARTWORKS[0]

export const pick = (v: Bilingual, lang: string): string => (lang === 'ja' ? v.ja : v.en)
export const imagePromptOf = (i: PgItem, lang: string): string => (i.kind === 'artwork' ? i.imagePrompt : pick(i.imagePrompt, lang))
