import type { Lang } from '@/lib/i18n'

const en = {
  eyebrow: 'Your private AI studio',
  title: 'One idea. More possibilities.',
  subtitle: 'Create with the models you choose. Keep what works for you.',
  templatesTitle: 'A head start for every idea.',
  templatesSubtitle: 'Choose a starting point. Make every detail your own.',
  creationsTitle: 'Your ideas, in progress.',
  creationsSubtitle: 'Pick up where you left off. Your work stays private.',
  prompt: 'Your prompt',
  useTemplate: 'Use a template',
  compare: 'Compare',
  continue: 'Continue',
  addModel: 'Add a model',
  compareModel: 'Add a model to compare',
  emptyTemplates: 'Start with a script in Studio, then choose a voice model.',
  type: 'Type',
  all: 'All',
  loading: 'Loading your library…',
  empty: 'Your projects will appear here.',
  emptyFilter: 'No projects of this type yet.',
  error: 'Your library could not be loaded. Please try again.',
  retry: 'Try again',
  signIn: 'Sign in to open your library',
  previous: 'Previous',
  next: 'Next',
  open: 'Open project',
  untitled: 'Untitled project',
  models: 'models',
  reference: 'Reference',
  lockedTemplates: 'Start a new project before applying a template. Your current generation continues in the background.',
  newCreation: 'New project',
}

type Copy = typeof en
const copy: Record<Lang, Copy> = {
  en,
  'zh-Hant': {
    eyebrow: '你的私人 AI 創作室', title: '一個靈感，更多可能。', subtitle: '用你選擇的模型創作，留下適合你的成果。',
    templatesTitle: '讓每個靈感，都有起點。', templatesSubtitle: '選擇範本，再把每個細節變成你的風格。',
    creationsTitle: '接著完成你的靈感。', creationsSubtitle: '從上次的進度繼續，作品只屬於你。',
    prompt: '你的提示詞', useTemplate: '使用範本', compare: '比較', continue: '繼續',
    addModel: '新增模型', compareModel: '新增模型一起比較', emptyTemplates: '先在工作室輸入腳本，再選擇語音模型。',
    type: '類型', all: '全部', loading: '正在載入作品庫…', empty: '你的專案會出現在這裡。', emptyFilter: '還沒有這種類型的專案。',
    error: '無法載入作品庫，請再試一次。', retry: '重試', signIn: '登入開啟作品庫', previous: '上一頁', next: '下一頁',
    open: '開啟專案', untitled: '未命名專案', models: '個模型', reference: '參考素材',
    lockedTemplates: '請先開始新專案，再套用範本。目前的生成會在背景繼續。', newCreation: '新專案',
  },
  'zh-Hans': {
    eyebrow: '你的私人 AI 创作室', title: '一个灵感，更多可能。', subtitle: '用你选择的模型创作，留下适合你的成果。',
    templatesTitle: '让每个灵感，都有起点。', templatesSubtitle: '选择模板，再把每个细节变成你的风格。',
    creationsTitle: '接着完成你的灵感。', creationsSubtitle: '从上次的进度继续，作品只属于你。',
    prompt: '你的提示词', useTemplate: '使用模板', compare: '比较', continue: '继续',
    addModel: '添加模型', compareModel: '添加模型一起比较', emptyTemplates: '先在工作室输入脚本，再选择语音模型。',
    type: '类型', all: '全部', loading: '正在加载作品库…', empty: '你的项目会出现在这里。', emptyFilter: '还没有这种类型的项目。',
    error: '无法加载作品库，请重试。', retry: '重试', signIn: '登录打开作品库', previous: '上一页', next: '下一页',
    open: '打开项目', untitled: '未命名项目', models: '个模型', reference: '参考素材',
    lockedTemplates: '请先开始新项目，再应用模板。目前的生成会在后台继续。', newCreation: '新项目',
  },
  ja: {
    eyebrow: 'あなただけの AI スタジオ', title: '一つのアイデアから、広がる可能性。', subtitle: '選んだモデルでつくり、自分に合う結果を残す。',
    templatesTitle: 'アイデアに、最初の一歩を。', templatesSubtitle: 'テンプレートを選んで、細部まで自分らしく。',
    creationsTitle: 'アイデアの続きを。', creationsSubtitle: '前回の続きから。作品はあなただけのものです。',
    prompt: 'プロンプト', useTemplate: 'テンプレートを使う', compare: '比較', continue: '続ける',
    addModel: 'モデルを追加', compareModel: '比較するモデルを追加', emptyTemplates: 'スタジオで原稿を入力し、音声モデルを選んでください。',
    type: '種類', all: 'すべて', loading: 'ライブラリを読み込み中…', empty: 'プロジェクトがここに表示されます。', emptyFilter: 'この種類のプロジェクトはまだありません。',
    error: 'ライブラリを読み込めませんでした。もう一度お試しください。', retry: '再試行', signIn: 'ログインしてライブラリを開く', previous: '前へ', next: '次へ',
    open: 'プロジェクトを開く', untitled: '無題のプロジェクト', models: 'モデル', reference: '参考素材',
    lockedTemplates: 'テンプレートを使うには新しいプロジェクトを始めてください。現在の生成はバックグラウンドで続きます。', newCreation: '新しいプロジェクト',
  },
  ko: {
    eyebrow: '나만의 AI 스튜디오', title: '하나의 아이디어, 더 많은 가능성.', subtitle: '원하는 모델로 만들고, 마음에 드는 결과를 남기세요.',
    templatesTitle: '모든 아이디어에 시작점을.', templatesSubtitle: '템플릿을 고르고 세부 사항을 나만의 스타일로 바꾸세요.',
    creationsTitle: '아이디어를 이어가세요.', creationsSubtitle: '이전 작업부터 계속하세요. 작품은 비공개로 유지됩니다.',
    prompt: '프롬프트', useTemplate: '템플릿 사용', compare: '비교', continue: '계속',
    addModel: '모델 추가', compareModel: '비교할 모델 추가', emptyTemplates: '스튜디오에서 대본을 입력한 뒤 음성 모델을 선택하세요.',
    type: '유형', all: '전체', loading: '라이브러리를 불러오는 중…', empty: '프로젝트가 여기에 표시됩니다.', emptyFilter: '이 유형의 프로젝트가 아직 없습니다.',
    error: '라이브러리를 불러오지 못했습니다. 다시 시도하세요.', retry: '다시 시도', signIn: '로그인하여 라이브러리 열기', previous: '이전', next: '다음',
    open: '프로젝트 열기', untitled: '제목 없는 프로젝트', models: '모델', reference: '참고 자료',
    lockedTemplates: '템플릿을 적용하려면 새 프로젝트를 시작하세요. 현재 생성은 백그라운드에서 계속됩니다.', newCreation: '새 프로젝트',
  },
}

export const xcreateStudioCopy = (lang: Lang): Copy => copy[lang]
