import type { Lang } from '@/lib/i18n'

const en = {
  eyebrow: 'Your private AI studio',
  title: 'One idea. More possibilities.',
  subtitle: 'Create with the models you choose. Keep what works for you.',
  templatesTitle: 'A head start for every idea.',
  templatesSubtitle: 'Choose a starting point. Make every detail your own.',
  creationsTitle: 'Your ideas, in progress.',
  creationsSubtitle: 'Pick up where you left off. Your creations stay private.',
  prompt: 'Your prompt',
  useTemplate: 'Use a template',
  create: 'Create',
  compare: 'Compare',
  continue: 'Continue',
  addModel: 'Add a model',
  compareModel: 'Add a model to compare',
  emptyTemplates: 'Start with a script in Create, then choose a voice model.',
  type: 'Type',
  all: 'All',
  loading: 'Loading your creations…',
  empty: 'Your creations will appear here.',
  emptyFilter: 'No creations of this type yet.',
  error: 'Your creations could not be loaded. Please try again.',
  retry: 'Try again',
  signIn: 'Sign in to see your creations',
  previous: 'Previous',
  next: 'Next',
  open: 'Open creation',
  untitled: 'Untitled creation',
  models: 'models',
  reference: 'Reference',
  lockedTemplates: 'Start a new creation before applying a template. Your current generation continues in the background.',
  newCreation: 'New creation',
}

type Copy = typeof en
const copy: Record<Lang, Copy> = {
  en,
  'zh-Hant': {
    eyebrow: '你的私人 AI 創作室', title: '一個靈感，更多可能。', subtitle: '用你選擇的模型創作，留下適合你的成果。',
    templatesTitle: '讓每個靈感，都有起點。', templatesSubtitle: '選擇範本，再把每個細節變成你的風格。',
    creationsTitle: '接著完成你的靈感。', creationsSubtitle: '從上次的進度繼續，作品只屬於你。',
    prompt: '你的提示詞', useTemplate: '使用範本', create: '創作', compare: '比較', continue: '繼續',
    addModel: '新增模型', compareModel: '新增模型一起比較', emptyTemplates: '先在創作頁輸入腳本，再選擇語音模型。',
    type: '類型', all: '全部', loading: '正在載入你的作品…', empty: '你的作品會出現在這裡。', emptyFilter: '還沒有這種類型的作品。',
    error: '無法載入作品，請再試一次。', retry: '重試', signIn: '登入查看你的作品', previous: '上一頁', next: '下一頁',
    open: '開啟作品', untitled: '未命名作品', models: '個模型', reference: '參考素材',
    lockedTemplates: '請先開始新創作，再套用範本。目前的生成會在背景繼續。', newCreation: '新創作',
  },
  'zh-Hans': {
    eyebrow: '你的私人 AI 创作室', title: '一个灵感，更多可能。', subtitle: '用你选择的模型创作，留下适合你的成果。',
    templatesTitle: '让每个灵感，都有起点。', templatesSubtitle: '选择模板，再把每个细节变成你的风格。',
    creationsTitle: '接着完成你的灵感。', creationsSubtitle: '从上次的进度继续，作品只属于你。',
    prompt: '你的提示词', useTemplate: '使用模板', create: '创作', compare: '比较', continue: '继续',
    addModel: '添加模型', compareModel: '添加模型一起比较', emptyTemplates: '先在创作页输入脚本，再选择语音模型。',
    type: '类型', all: '全部', loading: '正在加载你的作品…', empty: '你的作品会出现在这里。', emptyFilter: '还没有这种类型的作品。',
    error: '无法加载作品，请重试。', retry: '重试', signIn: '登录查看你的作品', previous: '上一页', next: '下一页',
    open: '打开作品', untitled: '未命名作品', models: '个模型', reference: '参考素材',
    lockedTemplates: '请先开始新创作，再应用模板。目前的生成会在后台继续。', newCreation: '新创作',
  },
  ja: {
    eyebrow: 'あなただけの AI スタジオ', title: '一つのアイデアから、広がる可能性。', subtitle: '選んだモデルでつくり、自分に合う結果を残す。',
    templatesTitle: 'アイデアに、最初の一歩を。', templatesSubtitle: 'テンプレートを選んで、細部まで自分らしく。',
    creationsTitle: 'アイデアの続きを。', creationsSubtitle: '前回の続きから。作品はあなただけのものです。',
    prompt: 'プロンプト', useTemplate: 'テンプレートを使う', create: '作成', compare: '比較', continue: '続ける',
    addModel: 'モデルを追加', compareModel: '比較するモデルを追加', emptyTemplates: '作成ページで原稿を入力し、音声モデルを選んでください。',
    type: '種類', all: 'すべて', loading: '作品を読み込み中…', empty: '作成した作品がここに表示されます。', emptyFilter: 'この種類の作品はまだありません。',
    error: '作品を読み込めませんでした。もう一度お試しください。', retry: '再試行', signIn: 'ログインして作品を見る', previous: '前へ', next: '次へ',
    open: '作品を開く', untitled: '無題の作品', models: 'モデル', reference: '参考素材',
    lockedTemplates: 'テンプレートを使うには新しい作成を始めてください。現在の生成はバックグラウンドで続きます。', newCreation: '新しく作成',
  },
  ko: {
    eyebrow: '나만의 AI 스튜디오', title: '하나의 아이디어, 더 많은 가능성.', subtitle: '원하는 모델로 만들고, 마음에 드는 결과를 남기세요.',
    templatesTitle: '모든 아이디어에 시작점을.', templatesSubtitle: '템플릿을 고르고 세부 사항을 나만의 스타일로 바꾸세요.',
    creationsTitle: '아이디어를 이어가세요.', creationsSubtitle: '이전 작업부터 계속하세요. 작품은 비공개로 유지됩니다.',
    prompt: '프롬프트', useTemplate: '템플릿 사용', create: '만들기', compare: '비교', continue: '계속',
    addModel: '모델 추가', compareModel: '비교할 모델 추가', emptyTemplates: '만들기에서 대본을 입력한 뒤 음성 모델을 선택하세요.',
    type: '유형', all: '전체', loading: '작품을 불러오는 중…', empty: '작품이 여기에 표시됩니다.', emptyFilter: '이 유형의 작품이 아직 없습니다.',
    error: '작품을 불러오지 못했습니다. 다시 시도하세요.', retry: '다시 시도', signIn: '로그인하여 작품 보기', previous: '이전', next: '다음',
    open: '작품 열기', untitled: '제목 없는 작품', models: '모델', reference: '참고 자료',
    lockedTemplates: '템플릿을 적용하려면 새 작업을 시작하세요. 현재 생성은 백그라운드에서 계속됩니다.', newCreation: '새로 만들기',
  },
}

export const xcreateStudioCopy = (lang: Lang): Copy => copy[lang]
